version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./NewsProxy/Dockerfile.backend
    ports:
      - "8000:8000"
    

  frontend:
    build:
      context: .
      dockerfile: ./NewsFrontend/Dockerfile.frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
