# Generated by Django 5.0.2 on 2024-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_proxy_app', '0002_alter_article_author_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
