# Generated by Django 5.0.2 on 2024-02-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_proxy_app', '0003_source_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_proxy_app.category'),
        ),
    ]
