# Generated by Django 5.0.2 on 2024-02-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_proxy_app', '0004_source_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
